import { readFile, writeFile } from "node:fs/promises";

// Canonical text stays in skills/ and the root notice file. The browser imports
// this generated module so kits remain available after the local server stops.
const skill = await readFile(
  new URL("../skills/poof-icon/SKILL.md", import.meta.url),
  "utf8",
);
const license = await readFile(
  new URL("../THIRD_PARTY_NOTICES.md", import.meta.url),
  "utf8",
);
const target = new URL(
  "../public/js/generated/kit-content.js",
  import.meta.url,
);
const expected = `// Generated by npm run sync:kit. Do not edit directly.\nexport const skill = ${JSON.stringify(skill)};\nexport const license = ${JSON.stringify(license)};\n`;

if (process.argv.includes("--check")) {
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== expected) {
    console.error(
      "Kit content is stale. Run npm run sync:kit and commit the generated file.",
    );
    process.exitCode = 1;
  } else console.log("Generated kit content is current.");
} else {
  await writeFile(target, expected);
  console.log("Updated public/js/generated/kit-content.js");
}
